server:
  port: 8081
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "FGsWIRTUTmzzQXvzdW7fPsyh8o0uSVYarI0n+/nOm45TkxW8E45iAHngZy44Kme5"