server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://172.17.0.2:3307/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

jwt:
  signerKey: "FGsWIRTUTmzzQXvzdW7fPsyh8o0uSVYarI0n+/nOm45TkxW8E45iAHngZy44Kme5"
  valid-duration: 30 #in seconds
  refreshable-duration: 3600 #seconds